import { type Complexity, shuffleInPlace } from "@flimflam/shared";

/**
 * Hot Take opinion prompts organized by complexity tier.
 * Each tier has 100+ statements.
 */

const KIDS_PROMPTS: string[] = [
  "Pizza is the best food ever",
  "Dogs are better pets than cats",
  "Summer is the best season",
  "Chocolate ice cream beats vanilla",
  "Superheroes are cooler than villains",
  "Breakfast for dinner is awesome",
  "Snow days are better than weekends",
  "The best pizza topping is pepperoni",
  "Cartoons are better than live action movies",
  "Staying up late is totally worth being tired",
  "Waffles are better than pancakes",
  "The beach is more fun than the mountains",
  "Recess is the most important part of school",
  "Cats are secretly plotting world domination",
  "Homework should be banned forever",
  "Robots would make great teachers",
  "Flying would be the best superpower",
  "Dinosaurs would make terrible pets",
  "The moon is made of cheese (if you believe hard enough)",
  "Naps are actually great once you're older",
  "Aliens definitely exist somewhere",
  "Unicorns are cooler than dragons",
  "Tacos are better than burritos",
  "Rainbows make everything better",
  "Being the youngest sibling is the best",
  "Video games are a real sport",
  "Mac and cheese is a perfect meal",
  "Swimming pools are better than the ocean",
  "Reading is secretly fun",
  "Candy should be a food group",
  "Jokes that make you groan are the best jokes",
  "Camping is better than hotels",
  "The best color is blue",
  "Legos are the greatest toy ever invented",
  "School lunch is underrated",
  "Sleeping in is the best feeling",
  "Trampolines are more fun than swings",
  "Every day should be your birthday",
  "Rainy days are secretly awesome",
  "Frogs are the cutest animals",
  "Peanut butter and jelly is a perfect sandwich",
  "Being tall is better than being short",
  "Bubble baths are superior to showers",
  "The best holiday is Halloween",
  "Stuffed animals have feelings",
  "Treehouses are the best hangout spots",
  "Cereal is better dry than with milk",
  "Socks with sandals are a bold fashion choice",
  "The floor is always lava",
  "Pillow forts are architectural masterpieces",
  "Glitter is impossible to clean up",
  "Hot chocolate is better than regular chocolate",
  "Being the line leader is a huge honor",
  "Goldfish are boring pets",
  "Pineapple on pizza is delicious",
  "Monkey bars are the ultimate test of strength",
  "Snow is better to play in than sand",
  "Scary movies are fun to watch",
  "Roller coasters are the best ride",
  "Wearing pajamas all day is living your best life",
  "Fruit snacks count as real fruit",
  "Blanket capes give you real powers",
  "The best day of the week is Friday",
  "Puddles are for jumping in",
  "Sprinkles make everything taste better",
  "Whispering is harder than yelling",
  "The best seat is the window seat",
  "Rewriting is harder than writing",
  "Slime is the greatest invention",
  "Fort building should be an Olympic sport",
  "Every food is better as a nugget shape",
  "Silly string should be used more often",
  "Gummy bears are the best candy",
  "Night time is better than daytime",
  "Libraries are underrated hangout spots",
  "Tag is the ultimate game",
  "Backwards day should be a real thing",
  "The tooth fairy has a great job",
  "Bubbles never get old",
  "Stickers are the best reward",
  "Sandcastles are real architecture",
  "Whistling is an underrated talent",
  "The last piece of pizza is the best one",
  "Bouncy castles should be everywhere",
  "Animals should be allowed in schools",
  "The funniest word is 'pickle'",
  "Slides are better than swings",
  "Friendship bracelets are the best gift",
  "Dessert should come first",
  "Clouds look like things on purpose",
  "The best instrument is the drums",
  "Water parks are better than theme parks",
  "Cartoons were better in the old days",
  "Grass stains are badges of honor",
  "Hide and seek is the ultimate test of patience",
  "The best snack is popcorn",
  "Magic tricks are real magic",
  "Fireflies are the coolest bugs",
  "Snowmen should last forever",
  "Chalk drawings on sidewalks are public art",
];

const STANDARD_PROMPTS: string[] = [
  "Social media has done more harm than good",
  "Working from home is better than working in an office",
  "Pineapple on pizza is a culinary crime",
  "The book is always better than the movie",
  "College is overrated for most careers",
  "Reality TV is a guilty pleasure worth having",
  "Breakfast is the most important meal of the day",
  "Texting is better than calling",
  "Money can buy happiness up to a point",
  "AI will create more jobs than it destroys",
  "Public transportation should be free",
  "Tipping culture has gone too far",
  "Hot dogs are sandwiches",
  "The toilet paper should go over, not under",
  "Cereal is technically a soup",
  "People who recline their seats on planes are monsters",
  "Working 4 days a week should be standard",
  "Streaming killed the movie theater experience",
  "Decaf coffee is pointless",
  "The Oxford comma is essential",
  "Socks and sandals are acceptable fashion",
  "Renting is smarter than buying a home right now",
  "Competitive gaming should be in the Olympics",
  "Homework does more harm than good",
  "Everyone should learn to code",
  "Pets are better than children (fight me)",
  "Time travel would cause more problems than it solves",
  "Aliens have definitely visited Earth",
  "Cold weather is better than hot weather",
  "Reboots and remakes are ruining entertainment",
  "The best music was made before 2000",
  "People should be required to take a test before using the internet",
  "Sarcasm is the highest form of wit",
  "The early bird does NOT actually get the worm",
  "Life was better before smartphones",
  "Karaoke is more fun when you're terrible at it",
  "Nice guys do finish last",
  "You should never meet your heroes",
  "Brunch is the most overrated meal",
  "People who arrive early to everything are suspicious",
  "Sequels are almost never as good as the original",
  "Living in a small town is better than a big city",
  "Camping is just paying to be homeless",
  "Everyone has a secret talent they haven't discovered",
  "Adulting should have come with a manual",
  "Dark chocolate is superior to milk chocolate",
  "Monday gets too much hate",
  "You can tell a lot about someone by their playlist",
  "Multitasking is a myth",
  "The best ideas happen in the shower",
  "Astrology is harmless fun, not science",
  "Everyone should travel solo at least once",
  "Fast food is a perfectly valid dinner choice",
  "Being average is underrated",
  "People bond more over shared dislikes than shared likes",
  "Unpopular opinions are usually just common sense",
  "The internet peaked around 2012",
  "Every generation thinks the next one is worse",
  "Coffee is just socially acceptable addiction",
  "Rain is actually better weather than sunshine",
  "The customer is rarely right",
  "It's okay to eat lunch alone",
  "New Year's resolutions are doomed to fail",
  "Your taste in music peaked in high school",
  "Silence is truly golden",
  "It's better to be overdressed than underdressed",
  "Free WiFi should be a human right",
  "Most meetings could have been an email",
  "Parallel parking should be on every driving test",
  "Sleeping is an underrated hobby",
  "Cursive writing is an obsolete skill",
  "Everyone should work in food service for at least one year",
  "Sundays are secretly the worst day of the week",
  "The snooze button does more harm than good",
  "Movie theater popcorn is worth the price",
  "Driving tests should be retaken every 10 years",
  "Sports rivalries bring out the worst in people",
  "GIFs are a legitimate form of communication",
  "Standing desks are overrated",
  "Birthday celebrations for adults are awkward",
  "Autocorrect causes more problems than it solves",
  "People who don't use turn signals are villains",
  "Board games are better than video games for socializing",
  "Having too many choices makes us less happy",
  "The gym on January 1st is a zoo",
  "Voicemails are obsolete",
  "Airports bring out the worst in humanity",
  "Documentaries are more entertaining than fiction",
  "Wedding culture has gotten out of control",
  "You shouldn't have to small talk with your barber",
  "Listening to podcasts at 2x speed is fine",
  "Group chats are chaotic evil",
  "The best part of a vacation is coming home",
  "Some people peak in high school and that's okay",
  "It's weird that we sing to our food on birthdays",
  "Wearing seatbelts in the back seat feels optional (but shouldn't)",
  "The five-second rule is definitely real",
  "People who correct your grammar are annoying",
  "Everyone should have a signature dish they can cook",
  "Online reviews cannot be trusted",
  "We should normalize changing your mind publicly",
];

const ADVANCED_PROMPTS: string[] = [
  "Democracy is the least bad system of government",
  "Absolute free speech should include hate speech",
  "Privacy is already dead — we should move on",
  "The death penalty is never justified",
  "Capitalism needs a complete overhaul, not patches",
  "We should colonize Mars even if it delays solving Earth's problems",
  "Designer babies will eventually be normalized and that's okay",
  "Social media companies should be regulated like utilities",
  "Universal basic income is inevitable",
  "Moral relativism makes ethical progress impossible",
  "We have a moral obligation to future generations we'll never meet",
  "Meritocracy is a comforting myth",
  "The simulation hypothesis is probably true",
  "Consciousness is an illusion",
  "We should be allowed to sell our own organs",
  "Cultural appropriation concerns stifle artistic expression",
  "Voting should be mandatory",
  "Intellectual property law does more harm than good",
  "Having children is an inherently selfish act",
  "Human nature makes utopia impossible",
  "Religion does more good than harm globally",
  "We should accept that some problems have no solutions",
  "The pursuit of happiness is overrated",
  "Power always corrupts — no exceptions",
  "Technology is evolving faster than our ethics can keep up",
  "Most charity is performative rather than effective",
  "Truth is less important to people than belonging",
  "Civil disobedience is a moral duty when laws are unjust",
  "We should radically rethink the concept of work",
  "History is written by the victors — and always will be",
  "Humans are fundamentally irrational and that's our strength",
  "The concept of genius is harmful and elitist",
  "Forgiveness is overrated as a virtue",
  "Nationalism is more dangerous now than ever",
  "We value confidence over competence",
  "The greatest threat to civilization is apathy, not malice",
  "Art should never be censored, regardless of content",
  "We should judge historical figures by today's standards",
  "Suffering is necessary for growth",
  "Most people would rather be comfortable than free",
  "Social mobility is largely an illusion",
  "Education systems were designed to create obedient workers",
  "Empathy without action is just entertainment",
  "The trolley problem reveals our moral bankruptcy",
  "We should genetically modify crops without restriction",
  "Cancel culture is mob justice with better PR",
  "Billionaires should not exist in a just society",
  "Marriage as an institution is outdated",
  "Privacy is more important than security",
  "Most political debates are really about values, not facts",
  "Science has become the new religion for many people",
  "The attention economy is destroying our ability to think deeply",
  "We should embrace genetic enhancement if it's safe",
  "Tradition for tradition's sake is intellectual laziness",
  "Most people confuse being informed with being wise",
  "The American Dream was always a myth for most",
  "We'll look back on factory farming as this era's greatest moral failing",
  "Academic credentials are an outdated proxy for competence",
  "The concept of retirement will disappear within 50 years",
  "We're too obsessed with productivity",
  "Nostalgia is a trap that prevents progress",
  "True equality is impossible — we should aim for equity instead",
  "The pursuit of longevity is humanity's most narcissistic project",
  "Most self-help advice is obvious wisdom repackaged",
  "Tribalism is humanity's most dangerous instinct",
  "We should prioritize beauty in urban design",
  "The most dangerous ideas are the ones we accept without questioning",
  "Ambition is as destructive as it is productive",
  "We fetishize busy-ness as a proxy for importance",
  "AI-generated art is still art",
  "The middle class is a political fiction",
  "Cynicism is just disappointed idealism",
  "We should separate medical research from profit motives",
  "Human rights are a Western invention being universalized",
  "The pen is mightier than the sword — but the algorithm beats both",
  "We underestimate how much our environment shapes our morality",
  "Philosophy should be a required subject in all schools",
  "Society punishes non-conformity while claiming to value individuality",
  "Our relationship with nature is fundamentally broken",
  "Fear drives more decisions than love",
  "The best leaders are those who don't want power",
  "Data is the new oil — and just as toxic when mishandled",
  "We'll never achieve world peace, but we should keep trying",
  "Most political arguments are proxy wars for deeper anxieties",
  "The nuclear family model is a historical anomaly, not a default",
  "Progress without wisdom is just sophisticated destruction",
  "We're living through the most peaceful era in human history",
  "Media literacy should be taught from elementary school",
  "The sharing economy is just rebranded exploitation",
  "Optimism without action is just fantasy",
  "We hold corporations to lower moral standards than individuals",
  "Language shapes reality more than we realize",
  "The biggest risk of AI isn't sentience — it's amplifying human bias",
  "We overvalue innovation and undervalue maintenance",
  "Money in politics is the root of democratic decay",
  "Children should have more rights and autonomy",
  "We should normalize failure as much as we celebrate success",
  "The most revolutionary act in modern life is paying attention",
  "Convenience is the enemy of sustainability",
  "Everyone is the villain in someone else's story",
  "Wisdom is knowing how little we actually know",
];

/**
 * Get prompts for a given complexity.
 */
export function getPrompts(complexity: Complexity): string[] {
  switch (complexity) {
    case "kids":
      return KIDS_PROMPTS;
    case "standard":
      return STANDARD_PROMPTS;
    case "advanced":
      return ADVANCED_PROMPTS;
  }
}

/**
 * Pick random prompts, avoiding repeats.
 */
export function pickRandomPrompts(
  complexity: Complexity,
  count: number,
  usedIndices: Set<number>,
): { prompt: string; index: number }[] {
  const allPrompts = getPrompts(complexity);
  const available = allPrompts
    .map((prompt, index) => ({ prompt, index }))
    .filter(({ index }) => !usedIndices.has(index));

  // Shuffle available
  shuffleInPlace(available);

  const picked = available.slice(0, count);

  // If not enough, reset used and pick more
  if (picked.length < count) {
    usedIndices.clear();
    const remaining = allPrompts
      .map((prompt, index) => ({ prompt, index }))
      .filter(({ index }) => !picked.some((p) => p.index === index));
    shuffleInPlace(remaining);
    picked.push(...remaining.slice(0, count - picked.length));
  }

  for (const p of picked) {
    usedIndices.add(p.index);
  }

  return picked;
}
