export interface SurveyAnswer {
  text: string;
  points: number;
  rank: number;
}

export interface Survey {
  question: string;
  answers: SurveyAnswer[];
}

export const KIDS_SURVEYS: Survey[] = [
  {
    question: "Name something you find at a playground",
    answers: [
      { text: "Slide", points: 30, rank: 1 },
      { text: "Swings", points: 25, rank: 2 },
      { text: "Monkey bars", points: 15, rank: 3 },
      { text: "Sandbox", points: 12, rank: 4 },
      { text: "Seesaw", points: 10, rank: 5 },
      { text: "Climbing wall", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a flavor of ice cream",
    answers: [
      { text: "Chocolate", points: 30, rank: 1 },
      { text: "Vanilla", points: 25, rank: 2 },
      { text: "Strawberry", points: 18, rank: 3 },
      { text: "Cookies and cream", points: 12, rank: 4 },
      { text: "Mint chocolate chip", points: 10, rank: 5 },
      { text: "Cookie dough", points: 5, rank: 6 },
    ],
  },
  {
    question: "Name an animal you might see at the zoo",
    answers: [
      { text: "Lion", points: 25, rank: 1 },
      { text: "Elephant", points: 22, rank: 2 },
      { text: "Giraffe", points: 18, rank: 3 },
      { text: "Monkey", points: 15, rank: 4 },
      { text: "Tiger", points: 12, rank: 5 },
      { text: "Bear", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you bring to school",
    answers: [
      { text: "Backpack", points: 28, rank: 1 },
      { text: "Lunch", points: 22, rank: 2 },
      { text: "Pencil", points: 18, rank: 3 },
      { text: "Books", points: 14, rank: 4 },
      { text: "Water bottle", points: 10, rank: 5 },
      { text: "Eraser", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a color of the rainbow",
    answers: [
      { text: "Red", points: 22, rank: 1 },
      { text: "Blue", points: 20, rank: 2 },
      { text: "Green", points: 16, rank: 3 },
      { text: "Yellow", points: 14, rank: 4 },
      { text: "Orange", points: 12, rank: 5 },
      { text: "Purple", points: 10, rank: 6 },
      { text: "Indigo", points: 6, rank: 7 },
    ],
  },
  {
    question: "Name a pet people keep at home",
    answers: [
      { text: "Dog", points: 35, rank: 1 },
      { text: "Cat", points: 28, rank: 2 },
      { text: "Fish", points: 15, rank: 3 },
      { text: "Hamster", points: 10, rank: 4 },
      { text: "Bird", points: 7, rank: 5 },
      { text: "Rabbit", points: 5, rank: 6 },
    ],
  },
  {
    question: "Name a fruit",
    answers: [
      { text: "Apple", points: 28, rank: 1 },
      { text: "Banana", points: 22, rank: 2 },
      { text: "Orange", points: 18, rank: 3 },
      { text: "Strawberry", points: 14, rank: 4 },
      { text: "Grape", points: 10, rank: 5 },
      { text: "Watermelon", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you do at a birthday party",
    answers: [
      { text: "Eat cake", points: 30, rank: 1 },
      { text: "Open presents", points: 25, rank: 2 },
      { text: "Play games", points: 18, rank: 3 },
      { text: "Sing happy birthday", points: 12, rank: 4 },
      { text: "Blow out candles", points: 10, rank: 5 },
      { text: "Dance", points: 5, rank: 6 },
    ],
  },
  {
    question: "Name a topping you put on pizza",
    answers: [
      { text: "Pepperoni", points: 30, rank: 1 },
      { text: "Cheese", points: 25, rank: 2 },
      { text: "Mushrooms", points: 15, rank: 3 },
      { text: "Sausage", points: 12, rank: 4 },
      { text: "Olives", points: 10, rank: 5 },
      { text: "Pineapple", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something that flies",
    answers: [
      { text: "Bird", points: 28, rank: 1 },
      { text: "Airplane", points: 25, rank: 2 },
      { text: "Butterfly", points: 15, rank: 3 },
      { text: "Helicopter", points: 12, rank: 4 },
      { text: "Kite", points: 10, rank: 5 },
      { text: "Bee", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a vegetable",
    answers: [
      { text: "Carrot", points: 25, rank: 1 },
      { text: "Broccoli", points: 22, rank: 2 },
      { text: "Corn", points: 18, rank: 3 },
      { text: "Peas", points: 14, rank: 4 },
      { text: "Potato", points: 12, rank: 5 },
      { text: "Tomato", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something you wear on your feet",
    answers: [
      { text: "Shoes", points: 30, rank: 1 },
      { text: "Socks", points: 28, rank: 2 },
      { text: "Sandals", points: 15, rank: 3 },
      { text: "Boots", points: 12, rank: 4 },
      { text: "Sneakers", points: 10, rank: 5 },
      { text: "Slippers", points: 5, rank: 6 },
    ],
  },
  {
    question: "Name a holiday",
    answers: [
      { text: "Christmas", points: 30, rank: 1 },
      { text: "Halloween", points: 22, rank: 2 },
      { text: "Thanksgiving", points: 16, rank: 3 },
      { text: "Easter", points: 12, rank: 4 },
      { text: "Fourth of July", points: 10, rank: 5 },
      { text: "Valentine's Day", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you do before going to bed",
    answers: [
      { text: "Brush teeth", points: 30, rank: 1 },
      { text: "Put on pajamas", points: 22, rank: 2 },
      { text: "Read a book", points: 18, rank: 3 },
      { text: "Take a bath", points: 14, rank: 4 },
      { text: "Say goodnight", points: 10, rank: 5 },
      { text: "Get a drink of water", points: 6, rank: 6 },
    ],
  },
  {
    question: "Name a type of weather",
    answers: [
      { text: "Rain", points: 28, rank: 1 },
      { text: "Snow", points: 25, rank: 2 },
      { text: "Sunny", points: 20, rank: 3 },
      { text: "Windy", points: 12, rank: 4 },
      { text: "Cloudy", points: 8, rank: 5 },
      { text: "Stormy", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name a type of candy",
    answers: [
      { text: "Chocolate bar", points: 28, rank: 1 },
      { text: "Gummy bears", points: 22, rank: 2 },
      { text: "Lollipop", points: 18, rank: 3 },
      { text: "Skittles", points: 14, rank: 4 },
      { text: "Jelly beans", points: 10, rank: 5 },
      { text: "Cotton candy", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you see in the sky at night",
    answers: [
      { text: "Stars", points: 35, rank: 1 },
      { text: "Moon", points: 30, rank: 2 },
      { text: "Airplane", points: 15, rank: 3 },
      { text: "Clouds", points: 10, rank: 4 },
      { text: "Satellite", points: 5, rank: 5 },
      { text: "Shooting star", points: 5, rank: 6 },
    ],
  },
  {
    question: "Name something you play with at recess",
    answers: [
      { text: "Ball", points: 28, rank: 1 },
      { text: "Jump rope", points: 22, rank: 2 },
      { text: "Tag", points: 18, rank: 3 },
      { text: "Swings", points: 14, rank: 4 },
      { text: "Frisbee", points: 10, rank: 5 },
      { text: "Hula hoop", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a superhero",
    answers: [
      { text: "Spider-Man", points: 28, rank: 1 },
      { text: "Batman", points: 25, rank: 2 },
      { text: "Superman", points: 20, rank: 3 },
      { text: "Wonder Woman", points: 12, rank: 4 },
      { text: "Iron Man", points: 10, rank: 5 },
      { text: "Captain America", points: 5, rank: 6 },
    ],
  },
  {
    question: "Name something you build with",
    answers: [
      { text: "Legos", points: 30, rank: 1 },
      { text: "Blocks", points: 25, rank: 2 },
      { text: "Sand", points: 15, rank: 3 },
      { text: "Clay", points: 12, rank: 4 },
      { text: "Cardboard", points: 10, rank: 5 },
      { text: "Sticks", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a breakfast food",
    answers: [
      { text: "Cereal", points: 28, rank: 1 },
      { text: "Pancakes", points: 22, rank: 2 },
      { text: "Eggs", points: 18, rank: 3 },
      { text: "Toast", points: 14, rank: 4 },
      { text: "Waffles", points: 10, rank: 5 },
      { text: "Bacon", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you find at the beach",
    answers: [
      { text: "Sand", points: 28, rank: 1 },
      { text: "Shells", points: 22, rank: 2 },
      { text: "Waves", points: 18, rank: 3 },
      { text: "Crabs", points: 14, rank: 4 },
      { text: "Seaweed", points: 10, rank: 5 },
      { text: "Driftwood", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a musical instrument",
    answers: [
      { text: "Piano", points: 28, rank: 1 },
      { text: "Guitar", points: 25, rank: 2 },
      { text: "Drums", points: 18, rank: 3 },
      { text: "Violin", points: 12, rank: 4 },
      { text: "Trumpet", points: 10, rank: 5 },
      { text: "Flute", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something you see in outer space",
    answers: [
      { text: "Stars", points: 28, rank: 1 },
      { text: "Planets", points: 25, rank: 2 },
      { text: "Moon", points: 18, rank: 3 },
      { text: "Sun", points: 12, rank: 4 },
      { text: "Asteroids", points: 10, rank: 5 },
      { text: "Rockets", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name a type of drink kids like",
    answers: [
      { text: "Juice", points: 30, rank: 1 },
      { text: "Chocolate milk", points: 25, rank: 2 },
      { text: "Lemonade", points: 16, rank: 3 },
      { text: "Soda", points: 12, rank: 4 },
      { text: "Water", points: 10, rank: 5 },
      { text: "Smoothie", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something you find in a classroom",
    answers: [
      { text: "Desks", points: 28, rank: 1 },
      { text: "Whiteboard", points: 22, rank: 2 },
      { text: "Books", points: 18, rank: 3 },
      { text: "Teacher", points: 14, rank: 4 },
      { text: "Clock", points: 10, rank: 5 },
      { text: "Globe", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a farm animal",
    answers: [
      { text: "Cow", points: 28, rank: 1 },
      { text: "Chicken", points: 22, rank: 2 },
      { text: "Pig", points: 18, rank: 3 },
      { text: "Horse", points: 14, rank: 4 },
      { text: "Sheep", points: 10, rank: 5 },
      { text: "Goat", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you do at a swimming pool",
    answers: [
      { text: "Swim", points: 30, rank: 1 },
      { text: "Dive", points: 22, rank: 2 },
      { text: "Splash", points: 16, rank: 3 },
      { text: "Float", points: 12, rank: 4 },
      { text: "Sunbathe", points: 10, rank: 5 },
      { text: "Play Marco Polo", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you do on a snow day",
    answers: [
      { text: "Build a snowman", points: 28, rank: 1 },
      { text: "Sled", points: 22, rank: 2 },
      { text: "Have a snowball fight", points: 18, rank: 3 },
      { text: "Drink hot chocolate", points: 14, rank: 4 },
      { text: "Watch movies", points: 10, rank: 5 },
      { text: "Make snow angels", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a Disney character",
    answers: [
      { text: "Mickey Mouse", points: 30, rank: 1 },
      { text: "Elsa", points: 22, rank: 2 },
      { text: "Cinderella", points: 16, rank: 3 },
      { text: "Buzz Lightyear", points: 12, rank: 4 },
      { text: "Simba", points: 10, rank: 5 },
      { text: "Ariel", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you put on a sandwich",
    answers: [
      { text: "Cheese", points: 28, rank: 1 },
      { text: "Lettuce", points: 20, rank: 2 },
      { text: "Tomato", points: 16, rank: 3 },
      { text: "Mustard", points: 14, rank: 4 },
      { text: "Mayo", points: 12, rank: 5 },
      { text: "Pickles", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a type of bug",
    answers: [
      { text: "Ant", points: 25, rank: 1 },
      { text: "Ladybug", points: 22, rank: 2 },
      { text: "Spider", points: 18, rank: 3 },
      { text: "Butterfly", points: 15, rank: 4 },
      { text: "Mosquito", points: 12, rank: 5 },
      { text: "Beetle", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you find in a forest",
    answers: [
      { text: "Trees", points: 30, rank: 1 },
      { text: "Animals", points: 22, rank: 2 },
      { text: "Mushrooms", points: 16, rank: 3 },
      { text: "Flowers", points: 12, rank: 4 },
      { text: "Rocks", points: 10, rank: 5 },
      { text: "Stream", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you use to draw",
    answers: [
      { text: "Crayons", points: 28, rank: 1 },
      { text: "Pencil", points: 25, rank: 2 },
      { text: "Markers", points: 18, rank: 3 },
      { text: "Colored pencils", points: 12, rank: 4 },
      { text: "Paint", points: 10, rank: 5 },
      { text: "Chalk", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name a type of sport",
    answers: [
      { text: "Soccer", points: 25, rank: 1 },
      { text: "Basketball", points: 22, rank: 2 },
      { text: "Baseball", points: 18, rank: 3 },
      { text: "Football", points: 15, rank: 4 },
      { text: "Swimming", points: 10, rank: 5 },
      { text: "Tennis", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you find in a treasure chest",
    answers: [
      { text: "Gold coins", points: 30, rank: 1 },
      { text: "Jewels", points: 25, rank: 2 },
      { text: "Necklace", points: 15, rank: 3 },
      { text: "Crown", points: 12, rank: 4 },
      { text: "Map", points: 10, rank: 5 },
      { text: "Diamonds", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you ride on",
    answers: [
      { text: "Bicycle", points: 28, rank: 1 },
      { text: "Horse", points: 22, rank: 2 },
      { text: "Roller coaster", points: 18, rank: 3 },
      { text: "Skateboard", points: 12, rank: 4 },
      { text: "Scooter", points: 10, rank: 5 },
      { text: "Bus", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something round",
    answers: [
      { text: "Ball", points: 30, rank: 1 },
      { text: "Circle", points: 20, rank: 2 },
      { text: "Earth", points: 16, rank: 3 },
      { text: "Pizza", points: 14, rank: 4 },
      { text: "Cookie", points: 10, rank: 5 },
      { text: "Wheel", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you see at a circus",
    answers: [
      { text: "Clown", points: 28, rank: 1 },
      { text: "Elephant", points: 22, rank: 2 },
      { text: "Trapeze", points: 16, rank: 3 },
      { text: "Lion", points: 14, rank: 4 },
      { text: "Juggler", points: 10, rank: 5 },
      { text: "Popcorn", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you do on the first day of school",
    answers: [
      { text: "Meet your teacher", points: 28, rank: 1 },
      { text: "Find your classroom", points: 22, rank: 2 },
      { text: "Make new friends", points: 18, rank: 3 },
      { text: "Get your supplies", points: 14, rank: 4 },
      { text: "Learn the rules", points: 10, rank: 5 },
      { text: "Wear new clothes", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something cold",
    answers: [
      { text: "Ice cream", points: 28, rank: 1 },
      { text: "Snow", points: 25, rank: 2 },
      { text: "Ice", points: 18, rank: 3 },
      { text: "Refrigerator", points: 12, rank: 4 },
      { text: "Popsicle", points: 10, rank: 5 },
      { text: "Winter wind", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name a type of hat",
    answers: [
      { text: "Baseball cap", points: 30, rank: 1 },
      { text: "Beanie", points: 22, rank: 2 },
      { text: "Cowboy hat", points: 16, rank: 3 },
      { text: "Sun hat", points: 12, rank: 4 },
      { text: "Top hat", points: 10, rank: 5 },
      { text: "Crown", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you take on a camping trip",
    answers: [
      { text: "Tent", points: 30, rank: 1 },
      { text: "Sleeping bag", points: 25, rank: 2 },
      { text: "Flashlight", points: 16, rank: 3 },
      { text: "Marshmallows", points: 12, rank: 4 },
      { text: "Bug spray", points: 10, rank: 5 },
      { text: "Firewood", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name an ocean animal",
    answers: [
      { text: "Shark", points: 28, rank: 1 },
      { text: "Dolphin", points: 25, rank: 2 },
      { text: "Whale", points: 18, rank: 3 },
      { text: "Turtle", points: 12, rank: 4 },
      { text: "Octopus", points: 10, rank: 5 },
      { text: "Jellyfish", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something you find in a lunchbox",
    answers: [
      { text: "Sandwich", points: 30, rank: 1 },
      { text: "Juice box", points: 22, rank: 2 },
      { text: "Apple", points: 16, rank: 3 },
      { text: "Chips", points: 12, rank: 4 },
      { text: "Crackers", points: 10, rank: 5 },
      { text: "Cookies", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you see at a parade",
    answers: [
      { text: "Floats", points: 28, rank: 1 },
      { text: "Marching band", points: 22, rank: 2 },
      { text: "Balloons", points: 18, rank: 3 },
      { text: "Candy", points: 14, rank: 4 },
      { text: "Flags", points: 10, rank: 5 },
      { text: "Costumes", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you find in the bathroom",
    answers: [
      { text: "Toilet", points: 28, rank: 1 },
      { text: "Sink", points: 22, rank: 2 },
      { text: "Toothbrush", points: 18, rank: 3 },
      { text: "Soap", points: 14, rank: 4 },
      { text: "Towel", points: 10, rank: 5 },
      { text: "Mirror", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a type of dessert",
    answers: [
      { text: "Cake", points: 28, rank: 1 },
      { text: "Ice cream", points: 25, rank: 2 },
      { text: "Cookies", points: 18, rank: 3 },
      { text: "Pie", points: 12, rank: 4 },
      { text: "Brownies", points: 10, rank: 5 },
      { text: "Pudding", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something you might be for Halloween",
    answers: [
      { text: "Ghost", points: 22, rank: 1 },
      { text: "Witch", points: 20, rank: 2 },
      { text: "Superhero", points: 18, rank: 3 },
      { text: "Vampire", points: 16, rank: 4 },
      { text: "Princess", points: 12, rank: 5 },
      { text: "Zombie", points: 7, rank: 6 },
      { text: "Pirate", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something with wheels",
    answers: [
      { text: "Car", points: 30, rank: 1 },
      { text: "Bicycle", points: 22, rank: 2 },
      { text: "Bus", points: 16, rank: 3 },
      { text: "Skateboard", points: 12, rank: 4 },
      { text: "Wagon", points: 10, rank: 5 },
      { text: "Roller skates", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you do at the park",
    answers: [
      { text: "Play", points: 28, rank: 1 },
      { text: "Walk the dog", points: 22, rank: 2 },
      { text: "Have a picnic", points: 18, rank: 3 },
      { text: "Ride a bike", points: 14, rank: 4 },
      { text: "Feed the ducks", points: 10, rank: 5 },
      { text: "Fly a kite", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something yellow",
    answers: [
      { text: "Sun", points: 30, rank: 1 },
      { text: "Banana", points: 25, rank: 2 },
      { text: "School bus", points: 15, rank: 3 },
      { text: "Lemon", points: 12, rank: 4 },
      { text: "Duck", points: 10, rank: 5 },
      { text: "Stars", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you use in the rain",
    answers: [
      { text: "Umbrella", points: 35, rank: 1 },
      { text: "Raincoat", points: 25, rank: 2 },
      { text: "Rain boots", points: 18, rank: 3 },
      { text: "Hood", points: 10, rank: 4 },
      { text: "Windshield wipers", points: 7, rank: 5 },
      { text: "Newspaper over head", points: 5, rank: 6 },
    ],
  },
  {
    question: "Name a type of shoe",
    answers: [
      { text: "Sneakers", points: 28, rank: 1 },
      { text: "Sandals", points: 22, rank: 2 },
      { text: "Boots", points: 18, rank: 3 },
      { text: "High heels", points: 14, rank: 4 },
      { text: "Flip flops", points: 10, rank: 5 },
      { text: "Cleats", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you see at a fair",
    answers: [
      { text: "Ferris wheel", points: 28, rank: 1 },
      { text: "Cotton candy", points: 22, rank: 2 },
      { text: "Games", points: 18, rank: 3 },
      { text: "Roller coaster", points: 14, rank: 4 },
      { text: "Funnel cake", points: 10, rank: 5 },
      { text: "Animals", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something that makes a loud noise",
    answers: [
      { text: "Thunder", points: 28, rank: 1 },
      { text: "Fireworks", points: 22, rank: 2 },
      { text: "Horn", points: 16, rank: 3 },
      { text: "Drum", points: 14, rank: 4 },
      { text: "Alarm clock", points: 10, rank: 5 },
      { text: "Siren", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you do in the summer",
    answers: [
      { text: "Swim", points: 28, rank: 1 },
      { text: "Go to the beach", points: 22, rank: 2 },
      { text: "Eat ice cream", points: 16, rank: 3 },
      { text: "Play outside", points: 14, rank: 4 },
      { text: "Go on vacation", points: 12, rank: 5 },
      { text: "Have a barbecue", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a game you play indoors",
    answers: [
      { text: "Video games", points: 28, rank: 1 },
      { text: "Board games", points: 22, rank: 2 },
      { text: "Card games", points: 18, rank: 3 },
      { text: "Hide and seek", points: 14, rank: 4 },
      { text: "Puzzles", points: 10, rank: 5 },
      { text: "Charades", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a type of tree",
    answers: [
      { text: "Oak", points: 25, rank: 1 },
      { text: "Pine", points: 22, rank: 2 },
      { text: "Maple", points: 18, rank: 3 },
      { text: "Palm", points: 14, rank: 4 },
      { text: "Apple tree", points: 12, rank: 5 },
      { text: "Willow", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something you take to the pool",
    answers: [
      { text: "Towel", points: 28, rank: 1 },
      { text: "Sunscreen", points: 22, rank: 2 },
      { text: "Swimsuit", points: 18, rank: 3 },
      { text: "Goggles", points: 14, rank: 4 },
      { text: "Pool noodle", points: 10, rank: 5 },
      { text: "Snacks", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a fairy tale character",
    answers: [
      { text: "Cinderella", points: 28, rank: 1 },
      { text: "Snow White", points: 22, rank: 2 },
      { text: "Big Bad Wolf", points: 16, rank: 3 },
      { text: "Goldilocks", points: 14, rank: 4 },
      { text: "Little Red Riding Hood", points: 10, rank: 5 },
      { text: "Sleeping Beauty", points: 10, rank: 6 },
    ],
  },
];

export const STANDARD_SURVEYS: Survey[] = [
  {
    question: "Name something people do before bed",
    answers: [
      { text: "Brush teeth", points: 28, rank: 1 },
      { text: "Watch TV", points: 22, rank: 2 },
      { text: "Read", points: 18, rank: 3 },
      { text: "Check phone", points: 14, rank: 4 },
      { text: "Shower", points: 10, rank: 5 },
      { text: "Set alarm", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a reason someone might be late to work",
    answers: [
      { text: "Traffic", points: 30, rank: 1 },
      { text: "Overslept", points: 25, rank: 2 },
      { text: "Car trouble", points: 15, rank: 3 },
      { text: "Kids", points: 12, rank: 4 },
      { text: "Weather", points: 10, rank: 5 },
      { text: "Lost keys", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something people lose",
    answers: [
      { text: "Keys", points: 28, rank: 1 },
      { text: "Phone", points: 22, rank: 2 },
      { text: "Wallet", points: 18, rank: 3 },
      { text: "Remote control", points: 14, rank: 4 },
      { text: "Glasses", points: 10, rank: 5 },
      { text: "Socks", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you find in a kitchen junk drawer",
    answers: [
      { text: "Batteries", points: 25, rank: 1 },
      { text: "Tape", points: 20, rank: 2 },
      { text: "Scissors", points: 18, rank: 3 },
      { text: "Rubber bands", points: 14, rank: 4 },
      { text: "Pens", points: 12, rank: 5 },
      { text: "Takeout menus", points: 6, rank: 6 },
      { text: "Matches", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something you do on a first date",
    answers: [
      { text: "Dinner", points: 30, rank: 1 },
      { text: "Movie", points: 22, rank: 2 },
      { text: "Coffee", points: 18, rank: 3 },
      { text: "Walk in the park", points: 12, rank: 4 },
      { text: "Drinks", points: 10, rank: 5 },
      { text: "Mini golf", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a place people go on vacation",
    answers: [
      { text: "Beach", points: 30, rank: 1 },
      { text: "Disney World", points: 22, rank: 2 },
      { text: "Las Vegas", points: 15, rank: 3 },
      { text: "Europe", points: 12, rank: 4 },
      { text: "Cruise", points: 10, rank: 5 },
      { text: "Camping", points: 6, rank: 6 },
      { text: "Mountains", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something people are afraid of",
    answers: [
      { text: "Spiders", points: 28, rank: 1 },
      { text: "Heights", points: 22, rank: 2 },
      { text: "Snakes", points: 18, rank: 3 },
      { text: "Public speaking", points: 14, rank: 4 },
      { text: "The dark", points: 10, rank: 5 },
      { text: "Flying", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you see at a wedding",
    answers: [
      { text: "Cake", points: 28, rank: 1 },
      { text: "Flowers", points: 22, rank: 2 },
      { text: "Bride", points: 18, rank: 3 },
      { text: "Dancing", points: 14, rank: 4 },
      { text: "Rings", points: 10, rank: 5 },
      { text: "Photographer", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you do at the gym",
    answers: [
      { text: "Lift weights", points: 28, rank: 1 },
      { text: "Run on treadmill", points: 25, rank: 2 },
      { text: "Stretch", points: 16, rank: 3 },
      { text: "Take a class", points: 12, rank: 4 },
      { text: "Use elliptical", points: 10, rank: 5 },
      { text: "Swim", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name a type of TV show",
    answers: [
      { text: "Sitcom", points: 25, rank: 1 },
      { text: "Drama", points: 22, rank: 2 },
      { text: "Reality", points: 18, rank: 3 },
      { text: "News", points: 14, rank: 4 },
      { text: "Game show", points: 12, rank: 5 },
      { text: "Documentary", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something people do on their phone while waiting",
    answers: [
      { text: "Social media", points: 30, rank: 1 },
      { text: "Play games", points: 22, rank: 2 },
      { text: "Text", points: 18, rank: 3 },
      { text: "Read news", points: 12, rank: 4 },
      { text: "Watch videos", points: 10, rank: 5 },
      { text: "Check email", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you find in a hotel room",
    answers: [
      { text: "Bed", points: 28, rank: 1 },
      { text: "TV", points: 22, rank: 2 },
      { text: "Bible", points: 16, rank: 3 },
      { text: "Mini fridge", points: 14, rank: 4 },
      { text: "Towels", points: 12, rank: 5 },
      { text: "Coffee maker", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a reason to call in sick to work",
    answers: [
      { text: "Flu", points: 28, rank: 1 },
      { text: "Headache", points: 20, rank: 2 },
      { text: "Stomach bug", points: 18, rank: 3 },
      { text: "Mental health day", points: 14, rank: 4 },
      { text: "Doctor appointment", points: 12, rank: 5 },
      { text: "Back pain", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you put in coffee",
    answers: [
      { text: "Sugar", points: 30, rank: 1 },
      { text: "Cream", points: 28, rank: 2 },
      { text: "Milk", points: 18, rank: 3 },
      { text: "Honey", points: 10, rank: 4 },
      { text: "Flavored syrup", points: 8, rank: 5 },
      { text: "Ice", points: 6, rank: 6 },
    ],
  },
  {
    question: "Name something people collect",
    answers: [
      { text: "Stamps", points: 25, rank: 1 },
      { text: "Coins", points: 22, rank: 2 },
      { text: "Baseball cards", points: 18, rank: 3 },
      { text: "Vinyl records", points: 14, rank: 4 },
      { text: "Action figures", points: 12, rank: 5 },
      { text: "Shoes", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something that makes you sneeze",
    answers: [
      { text: "Dust", points: 28, rank: 1 },
      { text: "Pollen", points: 25, rank: 2 },
      { text: "Pepper", points: 18, rank: 3 },
      { text: "Cat hair", points: 12, rank: 4 },
      { text: "Cold air", points: 10, rank: 5 },
      { text: "Perfume", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something you do on a road trip",
    answers: [
      { text: "Listen to music", points: 28, rank: 1 },
      { text: "Stop for food", points: 22, rank: 2 },
      { text: "Play car games", points: 16, rank: 3 },
      { text: "Sleep", points: 14, rank: 4 },
      { text: "Take photos", points: 10, rank: 5 },
      { text: "Argue over directions", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you associate with New Year's Eve",
    answers: [
      { text: "Countdown", points: 28, rank: 1 },
      { text: "Champagne", points: 22, rank: 2 },
      { text: "Fireworks", points: 18, rank: 3 },
      { text: "Kiss at midnight", points: 14, rank: 4 },
      { text: "Party", points: 10, rank: 5 },
      { text: "Resolutions", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you buy at a gas station",
    answers: [
      { text: "Gas", points: 35, rank: 1 },
      { text: "Snacks", points: 22, rank: 2 },
      { text: "Drinks", points: 18, rank: 3 },
      { text: "Lottery tickets", points: 10, rank: 4 },
      { text: "Cigarettes", points: 8, rank: 5 },
      { text: "Gum", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name a chore nobody likes doing",
    answers: [
      { text: "Dishes", points: 28, rank: 1 },
      { text: "Laundry", points: 22, rank: 2 },
      { text: "Cleaning the bathroom", points: 18, rank: 3 },
      { text: "Vacuuming", points: 14, rank: 4 },
      { text: "Mowing the lawn", points: 10, rank: 5 },
      { text: "Taking out trash", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something people eat at a barbecue",
    answers: [
      { text: "Hamburgers", points: 28, rank: 1 },
      { text: "Hot dogs", points: 25, rank: 2 },
      { text: "Ribs", points: 18, rank: 3 },
      { text: "Corn on the cob", points: 12, rank: 4 },
      { text: "Coleslaw", points: 10, rank: 5 },
      { text: "Potato salad", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something you grab when leaving the house",
    answers: [
      { text: "Keys", points: 30, rank: 1 },
      { text: "Phone", points: 28, rank: 2 },
      { text: "Wallet", points: 18, rank: 3 },
      { text: "Jacket", points: 10, rank: 4 },
      { text: "Sunglasses", points: 8, rank: 5 },
      { text: "Water bottle", points: 6, rank: 6 },
    ],
  },
  {
    question: "Name something people do at a concert",
    answers: [
      { text: "Sing along", points: 28, rank: 1 },
      { text: "Dance", points: 22, rank: 2 },
      { text: "Take videos", points: 18, rank: 3 },
      { text: "Drink", points: 14, rank: 4 },
      { text: "Cheer", points: 10, rank: 5 },
      { text: "Buy merchandise", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you do on a lazy Sunday",
    answers: [
      { text: "Sleep in", points: 30, rank: 1 },
      { text: "Watch TV", points: 22, rank: 2 },
      { text: "Eat brunch", points: 16, rank: 3 },
      { text: "Read", points: 12, rank: 4 },
      { text: "Lounge on couch", points: 10, rank: 5 },
      { text: "Order delivery", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people complain about",
    answers: [
      { text: "Weather", points: 25, rank: 1 },
      { text: "Traffic", points: 22, rank: 2 },
      { text: "Work", points: 18, rank: 3 },
      { text: "Prices", points: 14, rank: 4 },
      { text: "Politics", points: 12, rank: 5 },
      { text: "Neighbors", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something you do on your lunch break",
    answers: [
      { text: "Eat", points: 35, rank: 1 },
      { text: "Check phone", points: 20, rank: 2 },
      { text: "Go for a walk", points: 15, rank: 3 },
      { text: "Run errands", points: 12, rank: 4 },
      { text: "Nap", points: 10, rank: 5 },
      { text: "Chat with coworkers", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a popular app on people's phones",
    answers: [
      { text: "Instagram", points: 25, rank: 1 },
      { text: "TikTok", points: 22, rank: 2 },
      { text: "YouTube", points: 18, rank: 3 },
      { text: "Facebook", points: 14, rank: 4 },
      { text: "Snapchat", points: 12, rank: 5 },
      { text: "X/Twitter", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something you see in a doctor's office",
    answers: [
      { text: "Magazines", points: 25, rank: 1 },
      { text: "Scale", points: 20, rank: 2 },
      { text: "Stethoscope", points: 18, rank: 3 },
      { text: "Exam table", points: 14, rank: 4 },
      { text: "Posters", points: 12, rank: 5 },
      { text: "Cotton balls", points: 6, rank: 6 },
      { text: "Hand sanitizer", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something people do to relax after work",
    answers: [
      { text: "Watch TV", points: 28, rank: 1 },
      { text: "Have a drink", points: 22, rank: 2 },
      { text: "Exercise", points: 16, rank: 3 },
      { text: "Take a bath", points: 14, rank: 4 },
      { text: "Cook", points: 10, rank: 5 },
      { text: "Play video games", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a popular streaming service",
    answers: [
      { text: "Netflix", points: 30, rank: 1 },
      { text: "Disney+", points: 20, rank: 2 },
      { text: "Hulu", points: 16, rank: 3 },
      { text: "Amazon Prime", points: 14, rank: 4 },
      { text: "HBO Max", points: 10, rank: 5 },
      { text: "YouTube", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you find in a garage",
    answers: [
      { text: "Car", points: 28, rank: 1 },
      { text: "Tools", points: 22, rank: 2 },
      { text: "Lawnmower", points: 16, rank: 3 },
      { text: "Bicycles", points: 12, rank: 4 },
      { text: "Old boxes", points: 12, rank: 5 },
      { text: "Sports equipment", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a fast food restaurant",
    answers: [
      { text: "McDonald's", points: 30, rank: 1 },
      { text: "Chick-fil-A", points: 22, rank: 2 },
      { text: "Taco Bell", points: 16, rank: 3 },
      { text: "Wendy's", points: 12, rank: 4 },
      { text: "Burger King", points: 10, rank: 5 },
      { text: "Subway", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you do at a house party",
    answers: [
      { text: "Drink", points: 28, rank: 1 },
      { text: "Dance", points: 22, rank: 2 },
      { text: "Socialize", points: 18, rank: 3 },
      { text: "Play games", points: 12, rank: 4 },
      { text: "Eat snacks", points: 10, rank: 5 },
      { text: "Take selfies", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you check before leaving on a trip",
    answers: [
      { text: "Packed bags", points: 25, rank: 1 },
      { text: "Locked the door", points: 22, rank: 2 },
      { text: "Passport/ID", points: 18, rank: 3 },
      { text: "Turned off stove", points: 14, rank: 4 },
      { text: "Phone charger", points: 12, rank: 5 },
      { text: "Weather forecast", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something that annoys people in public",
    answers: [
      { text: "Loud talking", points: 28, rank: 1 },
      { text: "Cutting in line", points: 22, rank: 2 },
      { text: "Phone on speaker", points: 16, rank: 3 },
      { text: "Bad body odor", points: 14, rank: 4 },
      { text: "Chewing loudly", points: 10, rank: 5 },
      { text: "Blocking the aisle", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a famous movie franchise",
    answers: [
      { text: "Star Wars", points: 28, rank: 1 },
      { text: "Marvel/Avengers", points: 25, rank: 2 },
      { text: "Harry Potter", points: 18, rank: 3 },
      { text: "Fast and Furious", points: 12, rank: 4 },
      { text: "James Bond", points: 10, rank: 5 },
      { text: "Lord of the Rings", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something you buy at a grocery store every week",
    answers: [
      { text: "Milk", points: 28, rank: 1 },
      { text: "Bread", points: 22, rank: 2 },
      { text: "Eggs", points: 18, rank: 3 },
      { text: "Fruit", points: 12, rank: 4 },
      { text: "Chicken", points: 10, rank: 5 },
      { text: "Cereal", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people forget to do",
    answers: [
      { text: "Take out the trash", points: 25, rank: 1 },
      { text: "Reply to messages", points: 20, rank: 2 },
      { text: "Pay a bill", points: 18, rank: 3 },
      { text: "Lock the door", points: 15, rank: 4 },
      { text: "Bring an umbrella", points: 12, rank: 5 },
      { text: "Return a call", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people post about on social media",
    answers: [
      { text: "Food", points: 25, rank: 1 },
      { text: "Vacations", points: 22, rank: 2 },
      { text: "Selfies", points: 18, rank: 3 },
      { text: "Kids/family", points: 14, rank: 4 },
      { text: "Pets", points: 12, rank: 5 },
      { text: "Workouts", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name a comfort food",
    answers: [
      { text: "Mac and cheese", points: 28, rank: 1 },
      { text: "Pizza", points: 22, rank: 2 },
      { text: "Chicken soup", points: 16, rank: 3 },
      { text: "Ice cream", points: 14, rank: 4 },
      { text: "Mashed potatoes", points: 10, rank: 5 },
      { text: "Grilled cheese", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you tip for",
    answers: [
      { text: "Restaurant meal", points: 30, rank: 1 },
      { text: "Haircut", points: 22, rank: 2 },
      { text: "Taxi/rideshare", points: 16, rank: 3 },
      { text: "Delivery", points: 14, rank: 4 },
      { text: "Hotel housekeeping", points: 10, rank: 5 },
      { text: "Valet parking", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you sign",
    answers: [
      { text: "Check", points: 25, rank: 1 },
      { text: "Contract", points: 22, rank: 2 },
      { text: "Birthday card", points: 18, rank: 3 },
      { text: "Receipt", points: 14, rank: 4 },
      { text: "Permission slip", points: 12, rank: 5 },
      { text: "Yearbook", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something you put on a burger",
    answers: [
      { text: "Ketchup", points: 28, rank: 1 },
      { text: "Cheese", points: 22, rank: 2 },
      { text: "Lettuce", points: 16, rank: 3 },
      { text: "Pickles", points: 12, rank: 4 },
      { text: "Onions", points: 10, rank: 5 },
      { text: "Mustard", points: 7, rank: 6 },
      { text: "Tomato", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something that wakes you up in the middle of the night",
    answers: [
      { text: "Noise", points: 28, rank: 1 },
      { text: "Bad dream", points: 22, rank: 2 },
      { text: "Need the bathroom", points: 18, rank: 3 },
      { text: "Pet", points: 12, rank: 4 },
      { text: "Baby crying", points: 10, rank: 5 },
      { text: "Phone notification", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a sport people watch on TV",
    answers: [
      { text: "Football", points: 30, rank: 1 },
      { text: "Basketball", points: 22, rank: 2 },
      { text: "Baseball", points: 16, rank: 3 },
      { text: "Soccer", points: 12, rank: 4 },
      { text: "Tennis", points: 10, rank: 5 },
      { text: "Golf", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you wait in line for",
    answers: [
      { text: "Food", points: 25, rank: 1 },
      { text: "Rides at a theme park", points: 22, rank: 2 },
      { text: "Concert tickets", points: 16, rank: 3 },
      { text: "The bathroom", points: 14, rank: 4 },
      { text: "Check out at store", points: 12, rank: 5 },
      { text: "Black Friday deals", points: 6, rank: 6 },
      { text: "DMV", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something you keep in your car",
    answers: [
      { text: "Phone charger", points: 25, rank: 1 },
      { text: "Sunglasses", points: 22, rank: 2 },
      { text: "Napkins", points: 16, rank: 3 },
      { text: "Umbrella", points: 14, rank: 4 },
      { text: "Water bottle", points: 12, rank: 5 },
      { text: "Insurance card", points: 6, rank: 6 },
      { text: "Change", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something people search for online",
    answers: [
      { text: "Recipes", points: 25, rank: 1 },
      { text: "Products to buy", points: 22, rank: 2 },
      { text: "News", points: 18, rank: 3 },
      { text: "Directions", points: 14, rank: 4 },
      { text: "Health symptoms", points: 12, rank: 5 },
      { text: "Celebrity gossip", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something that gets stuck in your head",
    answers: [
      { text: "Song", points: 35, rank: 1 },
      { text: "Jingle", points: 20, rank: 2 },
      { text: "Catchy phrase", points: 15, rank: 3 },
      { text: "Melody", points: 12, rank: 4 },
      { text: "TV theme song", points: 10, rank: 5 },
      { text: "Nursery rhyme", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a New Year's resolution people break",
    answers: [
      { text: "Exercise more", points: 30, rank: 1 },
      { text: "Eat healthier", points: 22, rank: 2 },
      { text: "Save money", points: 18, rank: 3 },
      { text: "Quit smoking", points: 12, rank: 4 },
      { text: "Drink less", points: 10, rank: 5 },
      { text: "Read more", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you see at an airport",
    answers: [
      { text: "Airplanes", points: 28, rank: 1 },
      { text: "Luggage", points: 22, rank: 2 },
      { text: "Security checkpoint", points: 16, rank: 3 },
      { text: "Shops", points: 12, rank: 4 },
      { text: "Boarding gate", points: 10, rank: 5 },
      { text: "Delays on the board", points: 7, rank: 6 },
      { text: "Moving walkway", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something that has a remote control",
    answers: [
      { text: "TV", points: 35, rank: 1 },
      { text: "Garage door", points: 20, rank: 2 },
      { text: "Stereo", points: 15, rank: 3 },
      { text: "Ceiling fan", points: 12, rank: 4 },
      { text: "Air conditioner", points: 10, rank: 5 },
      { text: "Drone", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a type of cookie",
    answers: [
      { text: "Chocolate chip", points: 30, rank: 1 },
      { text: "Sugar cookie", points: 20, rank: 2 },
      { text: "Oatmeal raisin", points: 16, rank: 3 },
      { text: "Peanut butter", points: 14, rank: 4 },
      { text: "Snickerdoodle", points: 10, rank: 5 },
      { text: "Oreo", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people do in an elevator",
    answers: [
      { text: "Look at phone", points: 28, rank: 1 },
      { text: "Press a button", points: 22, rank: 2 },
      { text: "Stand in silence", points: 18, rank: 3 },
      { text: "Stare at the numbers", points: 12, rank: 4 },
      { text: "Make small talk", points: 10, rank: 5 },
      { text: "Hold the door", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something associated with a dentist visit",
    answers: [
      { text: "Drilling", points: 25, rank: 1 },
      { text: "X-rays", points: 20, rank: 2 },
      { text: "Pain", points: 18, rank: 3 },
      { text: "Cleaning", points: 15, rank: 4 },
      { text: "Waiting room", points: 12, rank: 5 },
      { text: "Free toothbrush", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you would find in a toolbox",
    answers: [
      { text: "Hammer", points: 28, rank: 1 },
      { text: "Screwdriver", points: 22, rank: 2 },
      { text: "Nails", points: 16, rank: 3 },
      { text: "Wrench", points: 14, rank: 4 },
      { text: "Tape measure", points: 10, rank: 5 },
      { text: "Pliers", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people binge-watch",
    answers: [
      { text: "Netflix series", points: 28, rank: 1 },
      { text: "Reality TV", points: 22, rank: 2 },
      { text: "Crime documentaries", points: 18, rank: 3 },
      { text: "Sitcoms", points: 12, rank: 4 },
      { text: "Anime", points: 10, rank: 5 },
      { text: "YouTube videos", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a reason people move to a new city",
    answers: [
      { text: "Job", points: 30, rank: 1 },
      { text: "Family", points: 22, rank: 2 },
      { text: "Cost of living", points: 16, rank: 3 },
      { text: "Weather", points: 12, rank: 4 },
      { text: "Relationship", points: 10, rank: 5 },
      { text: "School", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you put in a taco",
    answers: [
      { text: "Meat", points: 28, rank: 1 },
      { text: "Cheese", points: 22, rank: 2 },
      { text: "Lettuce", points: 16, rank: 3 },
      { text: "Salsa", points: 14, rank: 4 },
      { text: "Sour cream", points: 10, rank: 5 },
      { text: "Hot sauce", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you do on vacation that you never do at home",
    answers: [
      { text: "Sleep in late", points: 25, rank: 1 },
      { text: "Eat out every meal", points: 22, rank: 2 },
      { text: "Sightsee", points: 18, rank: 3 },
      { text: "Relax by the pool", points: 14, rank: 4 },
      { text: "Take photos of everything", points: 12, rank: 5 },
      { text: "Splurge on souvenirs", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something you need for a movie night at home",
    answers: [
      { text: "Popcorn", points: 30, rank: 1 },
      { text: "Blanket", points: 22, rank: 2 },
      { text: "Snacks", points: 16, rank: 3 },
      { text: "Couch", points: 12, rank: 4 },
      { text: "Drinks", points: 10, rank: 5 },
      { text: "Dimmed lights", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something that comes in pairs",
    answers: [
      { text: "Shoes", points: 28, rank: 1 },
      { text: "Socks", points: 25, rank: 2 },
      { text: "Gloves", points: 16, rank: 3 },
      { text: "Earrings", points: 12, rank: 4 },
      { text: "Eyes", points: 10, rank: 5 },
      { text: "Twins", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name a type of exercise",
    answers: [
      { text: "Running", points: 28, rank: 1 },
      { text: "Yoga", points: 22, rank: 2 },
      { text: "Push-ups", points: 16, rank: 3 },
      { text: "Cycling", points: 12, rank: 4 },
      { text: "Weight lifting", points: 12, rank: 5 },
      { text: "Swimming", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you bring to a potluck",
    answers: [
      { text: "Casserole", points: 25, rank: 1 },
      { text: "Salad", points: 22, rank: 2 },
      { text: "Dessert", points: 18, rank: 3 },
      { text: "Chips and dip", points: 14, rank: 4 },
      { text: "Rolls", points: 12, rank: 5 },
      { text: "Drinks", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something you find in your pockets at the end of the day",
    answers: [
      { text: "Phone", points: 28, rank: 1 },
      { text: "Keys", points: 22, rank: 2 },
      { text: "Change", points: 16, rank: 3 },
      { text: "Receipts", points: 14, rank: 4 },
      { text: "Lint", points: 10, rank: 5 },
      { text: "Gum wrapper", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something associated with Monday mornings",
    answers: [
      { text: "Coffee", points: 30, rank: 1 },
      { text: "Alarm clock", points: 22, rank: 2 },
      { text: "Traffic", points: 16, rank: 3 },
      { text: "Bad mood", points: 12, rank: 4 },
      { text: "Meetings", points: 10, rank: 5 },
      { text: "Snooze button", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a popular pizza chain",
    answers: [
      { text: "Domino's", points: 28, rank: 1 },
      { text: "Pizza Hut", points: 25, rank: 2 },
      { text: "Papa John's", points: 18, rank: 3 },
      { text: "Little Caesars", points: 12, rank: 4 },
      { text: "Papa Murphy's", points: 10, rank: 5 },
      { text: "Round Table", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something you find in a wallet",
    answers: [
      { text: "Cash", points: 28, rank: 1 },
      { text: "Credit cards", points: 25, rank: 2 },
      { text: "Driver's license", points: 18, rank: 3 },
      { text: "Photos", points: 12, rank: 4 },
      { text: "Receipts", points: 10, rank: 5 },
      { text: "Business cards", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name a reason to throw a party",
    answers: [
      { text: "Birthday", points: 30, rank: 1 },
      { text: "Graduation", points: 22, rank: 2 },
      { text: "Promotion", points: 15, rank: 3 },
      { text: "Housewarming", points: 12, rank: 4 },
      { text: "Holiday", points: 10, rank: 5 },
      { text: "Engagement", points: 6, rank: 6 },
      { text: "Super Bowl", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something you forget where you put",
    answers: [
      { text: "Keys", points: 28, rank: 1 },
      { text: "Phone", points: 25, rank: 2 },
      { text: "Glasses", points: 18, rank: 3 },
      { text: "Wallet", points: 12, rank: 4 },
      { text: "Remote control", points: 10, rank: 5 },
      { text: "Charger", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something every office has",
    answers: [
      { text: "Computer", points: 28, rank: 1 },
      { text: "Printer", points: 22, rank: 2 },
      { text: "Coffee machine", points: 18, rank: 3 },
      { text: "Desk", points: 14, rank: 4 },
      { text: "Chair", points: 10, rank: 5 },
      { text: "Stapler", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you see at a sporting event",
    answers: [
      { text: "Fans cheering", points: 25, rank: 1 },
      { text: "Hot dogs", points: 20, rank: 2 },
      { text: "Scoreboard", points: 18, rank: 3 },
      { text: "Jerseys", points: 15, rank: 4 },
      { text: "Beer", points: 12, rank: 5 },
      { text: "Foam finger", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something that runs out at the worst time",
    answers: [
      { text: "Phone battery", points: 30, rank: 1 },
      { text: "Gas", points: 22, rank: 2 },
      { text: "Toilet paper", points: 18, rank: 3 },
      { text: "Ink", points: 12, rank: 4 },
      { text: "Hot water", points: 10, rank: 5 },
      { text: "Deodorant", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you would save from a burning house",
    answers: [
      { text: "Family/pets", points: 30, rank: 1 },
      { text: "Phone", points: 22, rank: 2 },
      { text: "Photos", points: 16, rank: 3 },
      { text: "Wallet", points: 12, rank: 4 },
      { text: "Documents", points: 10, rank: 5 },
      { text: "Laptop", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a type of music genre",
    answers: [
      { text: "Pop", points: 25, rank: 1 },
      { text: "Hip hop", points: 22, rank: 2 },
      { text: "Rock", points: 18, rank: 3 },
      { text: "Country", points: 14, rank: 4 },
      { text: "R&B", points: 12, rank: 5 },
      { text: "Jazz", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something people do to cool off in summer",
    answers: [
      { text: "Go swimming", points: 30, rank: 1 },
      { text: "Turn on AC", points: 22, rank: 2 },
      { text: "Eat ice cream", points: 16, rank: 3 },
      { text: "Drink cold water", points: 12, rank: 4 },
      { text: "Sit in the shade", points: 10, rank: 5 },
      { text: "Use a fan", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people wear to a job interview",
    answers: [
      { text: "Suit", points: 30, rank: 1 },
      { text: "Dress shoes", points: 22, rank: 2 },
      { text: "Tie", points: 16, rank: 3 },
      { text: "Button-down shirt", points: 12, rank: 4 },
      { text: "Blazer", points: 10, rank: 5 },
      { text: "Watch", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you do when you can't sleep",
    answers: [
      { text: "Check your phone", points: 28, rank: 1 },
      { text: "Count sheep", points: 22, rank: 2 },
      { text: "Watch TV", points: 16, rank: 3 },
      { text: "Toss and turn", points: 12, rank: 4 },
      { text: "Get a snack", points: 12, rank: 5 },
      { text: "Read", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you associate with a rainy day",
    answers: [
      { text: "Umbrella", points: 28, rank: 1 },
      { text: "Staying inside", points: 22, rank: 2 },
      { text: "Hot cocoa", points: 16, rank: 3 },
      { text: "Puddles", points: 12, rank: 4 },
      { text: "Netflix", points: 12, rank: 5 },
      { text: "Thunder", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something that smells good",
    answers: [
      { text: "Fresh baked cookies", points: 28, rank: 1 },
      { text: "Flowers", points: 22, rank: 2 },
      { text: "Perfume", points: 18, rank: 3 },
      { text: "Coffee", points: 14, rank: 4 },
      { text: "Clean laundry", points: 10, rank: 5 },
      { text: "Pizza", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something people always have an opinion about",
    answers: [
      { text: "Politics", points: 28, rank: 1 },
      { text: "Sports teams", points: 20, rank: 2 },
      { text: "Food", points: 16, rank: 3 },
      { text: "Movies", points: 14, rank: 4 },
      { text: "Parenting", points: 12, rank: 5 },
      { text: "Weather", points: 10, rank: 6 },
    ],
  },
];

export const ADVANCED_SURVEYS: Survey[] = [
  {
    question: "Name something associated with Wall Street",
    answers: [
      { text: "Stocks", points: 28, rank: 1 },
      { text: "Money", points: 22, rank: 2 },
      { text: "Bull", points: 16, rank: 3 },
      { text: "Brokers", points: 14, rank: 4 },
      { text: "Crash", points: 10, rank: 5 },
      { text: "Wolf of Wall Street", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a famous speech",
    answers: [
      { text: "I Have a Dream", points: 35, rank: 1 },
      { text: "Gettysburg Address", points: 22, rank: 2 },
      { text: "Ask not what your country can do", points: 16, rank: 3 },
      { text: "We shall fight on the beaches", points: 10, rank: 4 },
      { text: "Yes we can", points: 10, rank: 5 },
      { text: "Tear down this wall", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something people argue about at Thanksgiving",
    answers: [
      { text: "Politics", points: 30, rank: 1 },
      { text: "Sports", points: 20, rank: 2 },
      { text: "Cooking", points: 16, rank: 3 },
      { text: "Money", points: 14, rank: 4 },
      { text: "Relationships", points: 12, rank: 5 },
      { text: "Where to sit", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a movie that made people cry",
    answers: [
      { text: "Titanic", points: 30, rank: 1 },
      { text: "The Notebook", points: 22, rank: 2 },
      { text: "Marley and Me", points: 15, rank: 3 },
      { text: "Forrest Gump", points: 12, rank: 4 },
      { text: "Up", points: 10, rank: 5 },
      { text: "Schindler's List", points: 6, rank: 6 },
      { text: "The Lion King", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something people lie about on their resume",
    answers: [
      { text: "Experience", points: 28, rank: 1 },
      { text: "Skills", points: 22, rank: 2 },
      { text: "Education", points: 18, rank: 3 },
      { text: "Job title", points: 14, rank: 4 },
      { text: "Salary", points: 10, rank: 5 },
      { text: "References", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a sign that someone is lying",
    answers: [
      { text: "Avoiding eye contact", points: 28, rank: 1 },
      { text: "Fidgeting", points: 22, rank: 2 },
      { text: "Sweating", points: 16, rank: 3 },
      { text: "Changing their story", points: 14, rank: 4 },
      { text: "Talking too fast", points: 12, rank: 5 },
      { text: "Touching their face", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something you would find in a CEO's office",
    answers: [
      { text: "Big desk", points: 28, rank: 1 },
      { text: "Computer", points: 20, rank: 2 },
      { text: "Awards and diplomas", points: 16, rank: 3 },
      { text: "Leather chair", points: 14, rank: 4 },
      { text: "Family photos", points: 12, rank: 5 },
      { text: "View of the city", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people do during a boring meeting",
    answers: [
      { text: "Check phone", points: 30, rank: 1 },
      { text: "Doodle", points: 22, rank: 2 },
      { text: "Daydream", points: 18, rank: 3 },
      { text: "Fall asleep", points: 12, rank: 4 },
      { text: "Send emails", points: 10, rank: 5 },
      { text: "Watch the clock", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a reason people get fired",
    answers: [
      { text: "Being late", points: 25, rank: 1 },
      { text: "Stealing", points: 22, rank: 2 },
      { text: "Poor performance", points: 18, rank: 3 },
      { text: "Lying", points: 14, rank: 4 },
      { text: "Insubordination", points: 12, rank: 5 },
      { text: "Gossiping", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something people regret saying in an argument",
    answers: [
      { text: "I hate you", points: 28, rank: 1 },
      { text: "Insults about appearance", points: 22, rank: 2 },
      { text: "Bringing up the past", points: 18, rank: 3 },
      { text: "Swear words", points: 14, rank: 4 },
      { text: "Comparing to someone else", points: 10, rank: 5 },
      { text: "Threatening to leave", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a city known for its nightlife",
    answers: [
      { text: "Las Vegas", points: 30, rank: 1 },
      { text: "New York", points: 22, rank: 2 },
      { text: "Miami", points: 16, rank: 3 },
      { text: "Los Angeles", points: 12, rank: 4 },
      { text: "Ibiza", points: 10, rank: 5 },
      { text: "Bangkok", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a famous brand everyone recognizes",
    answers: [
      { text: "Apple", points: 28, rank: 1 },
      { text: "Nike", points: 22, rank: 2 },
      { text: "Coca-Cola", points: 18, rank: 3 },
      { text: "McDonald's", points: 14, rank: 4 },
      { text: "Google", points: 10, rank: 5 },
      { text: "Amazon", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something associated with college life",
    answers: [
      { text: "Parties", points: 25, rank: 1 },
      { text: "Studying", points: 22, rank: 2 },
      { text: "Dorms", points: 18, rank: 3 },
      { text: "Student loans", points: 14, rank: 4 },
      { text: "Ramen noodles", points: 12, rank: 5 },
      { text: "All-nighters", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something people splurge on",
    answers: [
      { text: "Cars", points: 25, rank: 1 },
      { text: "Vacations", points: 22, rank: 2 },
      { text: "Shoes", points: 18, rank: 3 },
      { text: "Electronics", points: 14, rank: 4 },
      { text: "Jewelry", points: 12, rank: 5 },
      { text: "Food and dining", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something associated with a mid-life crisis",
    answers: [
      { text: "Sports car", points: 30, rank: 1 },
      { text: "Divorce", points: 20, rank: 2 },
      { text: "New haircut", points: 16, rank: 3 },
      { text: "Gym membership", points: 12, rank: 4 },
      { text: "Career change", points: 12, rank: 5 },
      { text: "Tattoo", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people hide from their partner",
    answers: [
      { text: "Spending", points: 28, rank: 1 },
      { text: "Past relationships", points: 22, rank: 2 },
      { text: "Junk food habits", points: 16, rank: 3 },
      { text: "Phone messages", points: 14, rank: 4 },
      { text: "Bad habits", points: 12, rank: 5 },
      { text: "Surprise gifts", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name a TV show everyone has watched",
    answers: [
      { text: "Friends", points: 28, rank: 1 },
      { text: "Game of Thrones", points: 22, rank: 2 },
      { text: "The Office", points: 18, rank: 3 },
      { text: "Seinfeld", points: 12, rank: 4 },
      { text: "Breaking Bad", points: 10, rank: 5 },
      { text: "Stranger Things", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something you negotiate the price of",
    answers: [
      { text: "Car", points: 30, rank: 1 },
      { text: "House", points: 25, rank: 2 },
      { text: "Salary", points: 18, rank: 3 },
      { text: "Flea market items", points: 10, rank: 4 },
      { text: "Cable bill", points: 10, rank: 5 },
      { text: "Furniture", points: 7, rank: 6 },
    ],
  },
  {
    question: "Name something that gets better with age",
    answers: [
      { text: "Wine", points: 30, rank: 1 },
      { text: "Cheese", points: 22, rank: 2 },
      { text: "Wisdom", points: 16, rank: 3 },
      { text: "Confidence", points: 12, rank: 4 },
      { text: "Relationships", points: 10, rank: 5 },
      { text: "Whiskey", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a profession that requires a lot of trust",
    answers: [
      { text: "Doctor", points: 28, rank: 1 },
      { text: "Lawyer", points: 22, rank: 2 },
      { text: "Accountant", points: 16, rank: 3 },
      { text: "Therapist", points: 14, rank: 4 },
      { text: "Pilot", points: 12, rank: 5 },
      { text: "Babysitter", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something people do to procrastinate",
    answers: [
      { text: "Browse social media", points: 30, rank: 1 },
      { text: "Watch TV", points: 22, rank: 2 },
      { text: "Snack", points: 16, rank: 3 },
      { text: "Clean", points: 12, rank: 4 },
      { text: "Nap", points: 10, rank: 5 },
      { text: "Online shopping", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a reason people unfollow someone on social media",
    answers: [
      { text: "Too many posts", points: 25, rank: 1 },
      { text: "Political rants", points: 22, rank: 2 },
      { text: "Bragging", points: 16, rank: 3 },
      { text: "Drama", points: 14, rank: 4 },
      { text: "Boring content", points: 12, rank: 5 },
      { text: "Misinformation", points: 6, rank: 6 },
      { text: "Breakup", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something associated with Silicon Valley",
    answers: [
      { text: "Tech companies", points: 28, rank: 1 },
      { text: "Start-ups", points: 22, rank: 2 },
      { text: "Billionaires", points: 16, rank: 3 },
      { text: "Coding", points: 12, rank: 4 },
      { text: "Venture capital", points: 12, rank: 5 },
      { text: "Stanford", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people do in a waiting room",
    answers: [
      { text: "Look at phone", points: 30, rank: 1 },
      { text: "Read magazines", points: 22, rank: 2 },
      { text: "Watch TV", points: 16, rank: 3 },
      { text: "Fill out paperwork", points: 12, rank: 4 },
      { text: "People watch", points: 10, rank: 5 },
      { text: "Worry", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people lie about on a dating profile",
    answers: [
      { text: "Age", points: 28, rank: 1 },
      { text: "Height", points: 22, rank: 2 },
      { text: "Photos", points: 18, rank: 3 },
      { text: "Job", points: 14, rank: 4 },
      { text: "Hobbies", points: 10, rank: 5 },
      { text: "Weight", points: 8, rank: 6 },
    ],
  },
  {
    question: "Name something that causes road rage",
    answers: [
      { text: "Getting cut off", points: 28, rank: 1 },
      { text: "Slow drivers", points: 22, rank: 2 },
      { text: "Tailgating", points: 16, rank: 3 },
      { text: "No turn signal", points: 14, rank: 4 },
      { text: "Traffic jams", points: 10, rank: 5 },
      { text: "Texting while driving", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a luxury brand",
    answers: [
      { text: "Gucci", points: 25, rank: 1 },
      { text: "Louis Vuitton", points: 22, rank: 2 },
      { text: "Chanel", points: 18, rank: 3 },
      { text: "Prada", points: 14, rank: 4 },
      { text: "Rolex", points: 12, rank: 5 },
      { text: "Hermès", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something people buy but rarely use",
    answers: [
      { text: "Gym membership", points: 28, rank: 1 },
      { text: "Exercise equipment", points: 22, rank: 2 },
      { text: "Kitchen gadgets", points: 16, rank: 3 },
      { text: "Books", points: 12, rank: 4 },
      { text: "Apps", points: 10, rank: 5 },
      { text: "Fancy clothes", points: 7, rank: 6 },
      { text: "Board games", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something that keeps you up at night",
    answers: [
      { text: "Stress", points: 28, rank: 1 },
      { text: "Caffeine", points: 20, rank: 2 },
      { text: "Phone", points: 16, rank: 3 },
      { text: "Noise", points: 14, rank: 4 },
      { text: "Worrying about money", points: 12, rank: 5 },
      { text: "Overthinking", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people pretend to like",
    answers: [
      { text: "Their boss's jokes", points: 28, rank: 1 },
      { text: "Gifts they don't want", points: 22, rank: 2 },
      { text: "Someone's cooking", points: 16, rank: 3 },
      { text: "Small talk", points: 12, rank: 4 },
      { text: "Family gatherings", points: 12, rank: 5 },
      { text: "Wine", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a classic board game",
    answers: [
      { text: "Monopoly", points: 30, rank: 1 },
      { text: "Scrabble", points: 20, rank: 2 },
      { text: "Clue", points: 16, rank: 3 },
      { text: "Risk", points: 12, rank: 4 },
      { text: "Chess", points: 12, rank: 5 },
      { text: "Life", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something associated with the 1990s",
    answers: [
      { text: "Boy bands", points: 25, rank: 1 },
      { text: "Dial-up internet", points: 22, rank: 2 },
      { text: "Floppy disks", points: 16, rank: 3 },
      { text: "Tamagotchi", points: 14, rank: 4 },
      { text: "Friends (TV show)", points: 12, rank: 5 },
      { text: "Frosted tips", points: 6, rank: 6 },
      { text: "Beanie Babies", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something you overhear strangers talking about",
    answers: [
      { text: "Their relationship", points: 25, rank: 1 },
      { text: "Work complaints", points: 22, rank: 2 },
      { text: "Plans for weekend", points: 18, rank: 3 },
      { text: "Health issues", points: 14, rank: 4 },
      { text: "Kids", points: 12, rank: 5 },
      { text: "Gossip", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something you would find in a time capsule from 2000",
    answers: [
      { text: "CD player", points: 25, rank: 1 },
      { text: "Flip phone", points: 22, rank: 2 },
      { text: "VHS tape", points: 16, rank: 3 },
      { text: "Newspaper", points: 14, rank: 4 },
      { text: "Photos", points: 12, rank: 5 },
      { text: "Coins", points: 6, rank: 6 },
      { text: "Game Boy", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something associated with Las Vegas",
    answers: [
      { text: "Gambling", points: 28, rank: 1 },
      { text: "Casinos", points: 22, rank: 2 },
      { text: "Shows", points: 16, rank: 3 },
      { text: "Weddings", points: 12, rank: 4 },
      { text: "Buffets", points: 12, rank: 5 },
      { text: "Neon lights", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people judge others for",
    answers: [
      { text: "Appearance", points: 28, rank: 1 },
      { text: "Grammar", points: 18, rank: 2 },
      { text: "Parenting", points: 16, rank: 3 },
      { text: "Diet choices", points: 14, rank: 4 },
      { text: "Music taste", points: 12, rank: 5 },
      { text: "Phone brand", points: 7, rank: 6 },
      { text: "Car they drive", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something associated with a stereotypical spy",
    answers: [
      { text: "Gadgets", points: 25, rank: 1 },
      { text: "Disguises", points: 22, rank: 2 },
      { text: "Secret missions", points: 18, rank: 3 },
      { text: "Sunglasses", points: 14, rank: 4 },
      { text: "Code names", points: 12, rank: 5 },
      { text: "Martini", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name a country people dream of visiting",
    answers: [
      { text: "Italy", points: 25, rank: 1 },
      { text: "Japan", points: 22, rank: 2 },
      { text: "France", points: 18, rank: 3 },
      { text: "Australia", points: 14, rank: 4 },
      { text: "Greece", points: 12, rank: 5 },
      { text: "Iceland", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something people do when they're nervous",
    answers: [
      { text: "Bite nails", points: 28, rank: 1 },
      { text: "Sweat", points: 22, rank: 2 },
      { text: "Pace", points: 16, rank: 3 },
      { text: "Fidget", points: 12, rank: 4 },
      { text: "Talk too much", points: 12, rank: 5 },
      { text: "Avoid eye contact", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name an occupation that people wanted to be as kids but didn't become",
    answers: [
      { text: "Astronaut", points: 25, rank: 1 },
      { text: "Professional athlete", points: 22, rank: 2 },
      { text: "Doctor", points: 18, rank: 3 },
      { text: "Rock star", points: 14, rank: 4 },
      { text: "Firefighter", points: 12, rank: 5 },
      { text: "Actor", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name a word people use that makes them sound smart",
    answers: [
      { text: "Subsequently", points: 22, rank: 1 },
      { text: "Utilize", points: 20, rank: 2 },
      { text: "Per se", points: 18, rank: 3 },
      { text: "Henceforth", points: 16, rank: 4 },
      { text: "Paradigm", points: 12, rank: 5 },
      { text: "Synergy", points: 7, rank: 6 },
      { text: "Albeit", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something associated with a haunted house",
    answers: [
      { text: "Ghosts", points: 28, rank: 1 },
      { text: "Creaky doors", points: 20, rank: 2 },
      { text: "Cobwebs", points: 18, rank: 3 },
      { text: "Screams", points: 14, rank: 4 },
      { text: "Dark hallways", points: 10, rank: 5 },
      { text: "Bats", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people argue about at work",
    answers: [
      { text: "Thermostat temperature", points: 25, rank: 1 },
      { text: "Deadlines", points: 22, rank: 2 },
      { text: "Credit for ideas", points: 16, rank: 3 },
      { text: "Meeting times", points: 14, rank: 4 },
      { text: "Kitchen cleanliness", points: 12, rank: 5 },
      { text: "Parking spots", points: 6, rank: 6 },
      { text: "Music volume", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something associated with a cliche movie villain",
    answers: [
      { text: "Evil laugh", points: 28, rank: 1 },
      { text: "Cat on their lap", points: 20, rank: 2 },
      { text: "Monologue", points: 16, rank: 3 },
      { text: "Scar", points: 14, rank: 4 },
      { text: "Secret lair", points: 12, rank: 5 },
      { text: "Cape", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people brag about at a high school reunion",
    answers: [
      { text: "Their job", points: 28, rank: 1 },
      { text: "Their kids", points: 22, rank: 2 },
      { text: "Weight loss", points: 16, rank: 3 },
      { text: "Travel", points: 12, rank: 4 },
      { text: "Their house", points: 12, rank: 5 },
      { text: "Their car", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something that makes a bad roommate",
    answers: [
      { text: "Not cleaning up", points: 28, rank: 1 },
      { text: "Being too loud", points: 22, rank: 2 },
      { text: "Eating your food", points: 16, rank: 3 },
      { text: "Not paying rent", points: 14, rank: 4 },
      { text: "Having people over constantly", points: 10, rank: 5 },
      { text: "Passive-aggressive notes", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a conspiracy theory people believe",
    answers: [
      { text: "Moon landing was fake", points: 25, rank: 1 },
      { text: "Flat earth", points: 22, rank: 2 },
      { text: "Area 51 aliens", points: 18, rank: 3 },
      { text: "JFK assassination", points: 14, rank: 4 },
      { text: "Illuminati", points: 12, rank: 5 },
      { text: "Bigfoot", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something people do the night before an exam",
    answers: [
      { text: "Cram", points: 30, rank: 1 },
      { text: "Panic", points: 22, rank: 2 },
      { text: "Lose sleep", points: 16, rank: 3 },
      { text: "Drink coffee", points: 12, rank: 4 },
      { text: "Pray", points: 10, rank: 5 },
      { text: "Give up and go to bed", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name a red flag on a first date",
    answers: [
      { text: "Rude to the waiter", points: 28, rank: 1 },
      { text: "Constantly on phone", points: 22, rank: 2 },
      { text: "Talks only about themselves", points: 18, rank: 3 },
      { text: "Mentions their ex", points: 12, rank: 4 },
      { text: "Late without apology", points: 10, rank: 5 },
      { text: "Doesn't ask questions", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people do at 2 AM that they regret",
    answers: [
      { text: "Texting an ex", points: 28, rank: 1 },
      { text: "Eating junk food", points: 22, rank: 2 },
      { text: "Online shopping", points: 16, rank: 3 },
      { text: "Staying up even later", points: 12, rank: 4 },
      { text: "Posting on social media", points: 12, rank: 5 },
      { text: "Watching one more episode", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something associated with a stereotypical tourist",
    answers: [
      { text: "Camera", points: 25, rank: 1 },
      { text: "Fanny pack", points: 22, rank: 2 },
      { text: "Map", points: 18, rank: 3 },
      { text: "Hawaiian shirt", points: 14, rank: 4 },
      { text: "Selfie stick", points: 12, rank: 5 },
      { text: "Sandals with socks", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something people pay way too much for",
    answers: [
      { text: "Coffee", points: 25, rank: 1 },
      { text: "Movie theater popcorn", points: 22, rank: 2 },
      { text: "Concert tickets", points: 16, rank: 3 },
      { text: "College tuition", points: 14, rank: 4 },
      { text: "Airport food", points: 12, rank: 5 },
      { text: "Cable TV", points: 6, rank: 6 },
      { text: "Printer ink", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something people say when they get pulled over",
    answers: [
      { text: "Was I speeding?", points: 28, rank: 1 },
      { text: "I didn't know the limit", points: 22, rank: 2 },
      { text: "I'm sorry officer", points: 16, rank: 3 },
      { text: "I'm late for work", points: 14, rank: 4 },
      { text: "I'll slow down", points: 10, rank: 5 },
      { text: "Everyone else was going that fast", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something that goes viral on the internet",
    answers: [
      { text: "Cat videos", points: 25, rank: 1 },
      { text: "Dance challenges", points: 22, rank: 2 },
      { text: "Memes", points: 18, rank: 3 },
      { text: "Celebrity drama", points: 14, rank: 4 },
      { text: "Fail compilations", points: 12, rank: 5 },
      { text: "Outrage stories", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something associated with a hostage negotiation in movies",
    answers: [
      { text: "Megaphone", points: 25, rank: 1 },
      { text: "SWAT team", points: 22, rank: 2 },
      { text: "Pizza delivery", points: 16, rank: 3 },
      { text: "Phone call", points: 14, rank: 4 },
      { text: "Helicopter", points: 12, rank: 5 },
      { text: "Demands list", points: 6, rank: 6 },
      { text: "Deadline timer", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name an unwritten rule of social etiquette",
    answers: [
      { text: "Don't talk with your mouth full", points: 25, rank: 1 },
      { text: "Hold the door", points: 22, rank: 2 },
      { text: "Say please and thank you", points: 18, rank: 3 },
      { text: "Don't stare", points: 14, rank: 4 },
      { text: "Give personal space", points: 12, rank: 5 },
      { text: "Tip your server", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something associated with the apocalypse",
    answers: [
      { text: "Zombies", points: 25, rank: 1 },
      { text: "Nuclear war", points: 22, rank: 2 },
      { text: "Bunkers", points: 16, rank: 3 },
      { text: "Food shortage", points: 14, rank: 4 },
      { text: "Asteroid", points: 12, rank: 5 },
      { text: "Virus", points: 6, rank: 6 },
      { text: "Looting", points: 5, rank: 7 },
    ],
  },
  {
    question: "Name something a hotel concierge gets asked for",
    answers: [
      { text: "Restaurant recommendations", points: 28, rank: 1 },
      { text: "Taxi/ride", points: 22, rank: 2 },
      { text: "Directions", points: 16, rank: 3 },
      { text: "Show tickets", points: 12, rank: 4 },
      { text: "Extra towels", points: 12, rank: 5 },
      { text: "Late checkout", points: 10, rank: 6 },
    ],
  },
  {
    question: "Name something people pretend to understand but don't",
    answers: [
      { text: "Cryptocurrency", points: 25, rank: 1 },
      { text: "Art", points: 20, rank: 2 },
      { text: "Wine tasting", points: 18, rank: 3 },
      { text: "Stock market", points: 16, rank: 4 },
      { text: "Terms and conditions", points: 12, rank: 5 },
      { text: "Quantum physics", points: 9, rank: 6 },
    ],
  },
  {
    question: "Name something associated with being rich",
    answers: [
      { text: "Big house", points: 25, rank: 1 },
      { text: "Fancy car", points: 22, rank: 2 },
      { text: "Designer clothes", points: 18, rank: 3 },
      { text: "Yacht", points: 14, rank: 4 },
      { text: "Private jet", points: 12, rank: 5 },
      { text: "Butler", points: 9, rank: 6 },
    ],
  },
];
