import { type Complexity, pickRandom } from "@flimflam/shared";

/**
 * Word bank for Quick Draw, organized by complexity tier.
 * Each tier has 150+ words.
 */

const KIDS_WORDS: string[] = [
  // Animals
  "cat",
  "dog",
  "fish",
  "bird",
  "frog",
  "duck",
  "pig",
  "cow",
  "horse",
  "bunny",
  "bee",
  "ant",
  "bear",
  "lion",
  "tiger",
  "shark",
  "whale",
  "snake",
  "mouse",
  "owl",
  "penguin",
  "monkey",
  "elephant",
  "giraffe",
  "zebra",
  "turtle",
  "butterfly",
  "ladybug",
  "dinosaur",
  "dragon",
  // Food
  "apple",
  "banana",
  "pizza",
  "cake",
  "cookie",
  "ice cream",
  "hot dog",
  "donut",
  "watermelon",
  "sandwich",
  "popcorn",
  "candy",
  "burger",
  "taco",
  "pie",
  "egg",
  "carrot",
  "corn",
  "grapes",
  "cherry",
  // Objects
  "ball",
  "star",
  "heart",
  "house",
  "car",
  "train",
  "boat",
  "plane",
  "rocket",
  "rainbow",
  "sun",
  "moon",
  "cloud",
  "tree",
  "flower",
  "book",
  "hat",
  "shoe",
  "clock",
  "key",
  "lamp",
  "bed",
  "chair",
  "table",
  "door",
  "window",
  "cup",
  "spoon",
  "fork",
  "kite",
  // Activities
  "swimming",
  "running",
  "dancing",
  "singing",
  "jumping",
  "sleeping",
  "eating",
  "reading",
  "painting",
  "flying",
  // Places
  "beach",
  "park",
  "school",
  "castle",
  "mountain",
  "island",
  "farm",
  "zoo",
  "circus",
  "playground",
  // Characters/Things
  "robot",
  "pirate",
  "princess",
  "ninja",
  "ghost",
  "alien",
  "superhero",
  "wizard",
  "mermaid",
  "fairy",
  // Nature
  "river",
  "ocean",
  "volcano",
  "cave",
  "forest",
  "desert",
  "snowflake",
  "tornado",
  "lightning",
  "waterfall",
  // More objects
  "balloon",
  "umbrella",
  "guitar",
  "drum",
  "whistle",
  "crown",
  "sword",
  "shield",
  "treasure",
  "map",
  "camera",
  "phone",
  "TV",
  "computer",
  "bicycle",
  "skateboard",
  "sled",
  "surfboard",
  "tent",
  "campfire",
  // Body parts
  "eye",
  "nose",
  "mouth",
  "hand",
  "foot",
  "ear",
  // Misc
  "smile",
  "teardrop",
  "fireworks",
  "present",
  "candle",
];

const STANDARD_WORDS: string[] = [
  // Actions/Concepts
  "parachute",
  "telescope",
  "microscope",
  "compass",
  "anchor",
  "lighthouse",
  "windmill",
  "hourglass",
  "chandelier",
  "hammock",
  "trampoline",
  "escalator",
  "elevator",
  "ferris wheel",
  "rollercoaster",
  "carousel",
  "treadmill",
  "seesaw",
  // Animals (harder)
  "octopus",
  "scorpion",
  "chameleon",
  "flamingo",
  "peacock",
  "porcupine",
  "platypus",
  "armadillo",
  "hedgehog",
  "seahorse",
  "jellyfish",
  "lobster",
  "pelican",
  "toucan",
  "iguana",
  "koala",
  "sloth",
  "cheetah",
  "rhino",
  "gorilla",
  // Food (harder)
  "spaghetti",
  "pretzel",
  "waffle",
  "croissant",
  "sushi",
  "burrito",
  "nachos",
  "pancake",
  "cupcake",
  "lollipop",
  "popsicle",
  "milkshake",
  "smoothie",
  "french fries",
  "onion rings",
  "cinnamon roll",
  // Objects (harder)
  "binoculars",
  "stethoscope",
  "calculator",
  "headphones",
  "microphone",
  "megaphone",
  "typewriter",
  "scissors",
  "stapler",
  "paperclip",
  "magnet",
  "battery",
  "flashlight",
  "lantern",
  "candelabra",
  "trophy",
  "medal",
  "backpack",
  "briefcase",
  "wallet",
  // Vehicles
  "submarine",
  "helicopter",
  "motorcycle",
  "ambulance",
  "firetruck",
  "bulldozer",
  "spaceship",
  "sailboat",
  "canoe",
  "hovercraft",
  // Buildings/Places
  "skyscraper",
  "pyramid",
  "igloo",
  "treehouse",
  "bridge",
  "tunnel",
  "stadium",
  "greenhouse",
  "aquarium",
  "museum",
  "library",
  "hospital",
  // Activities
  "bowling",
  "surfing",
  "skiing",
  "archery",
  "fencing",
  "karate",
  "gymnastics",
  "juggling",
  "magic trick",
  "yoga",
  // Nature
  "cactus",
  "palm tree",
  "mushroom",
  "coral reef",
  "geyser",
  "glacier",
  "stalactite",
  "aurora",
  "eclipse",
  "comet",
  // Occupations
  "astronaut",
  "chef",
  "firefighter",
  "detective",
  "photographer",
  "lifeguard",
  "conductor",
  "pilot",
  "surgeon",
  "magician",
  // Concepts
  "gravity",
  "shadow",
  "reflection",
  "whirlpool",
  "mirage",
  "illusion",
  "maze",
  "puzzle",
  "domino effect",
  "chain reaction",
  // Music
  "piano",
  "violin",
  "trumpet",
  "saxophone",
  "accordion",
  "harp",
  "xylophone",
  "tambourine",
  "bongo drums",
  // Misc
  "dreamcatcher",
  "boomerang",
  "yo-yo",
  "pinwheel",
  "kaleidoscope",
  "snow globe",
  "jack-in-the-box",
  "matryoshka",
  "origami",
  "sandcastle",
];

const ADVANCED_WORDS: string[] = [
  // Abstract concepts
  "democracy",
  "evolution",
  "entropy",
  "paradox",
  "nostalgia",
  "deja vu",
  "serendipity",
  "metamorphosis",
  "procrastination",
  "claustrophobia",
  "vertigo",
  "epiphany",
  "irony",
  "karma",
  "renaissance",
  "utopia",
  "dystopia",
  "anarchy",
  "philosophy",
  "existentialism",
  // Complex objects
  "guillotine",
  "gramophone",
  "periscope",
  "astrolabe",
  "sundial",
  "abacus",
  "pendulum",
  "gyroscope",
  "theodolite",
  "sextant",
  "catapult",
  "trebuchet",
  "crossbow",
  "battering ram",
  "drawbridge",
  // Science
  "DNA helix",
  "atom",
  "black hole",
  "supernova",
  "nebula",
  "chromosome",
  "neuron",
  "photosynthesis",
  "mitosis",
  "tectonic plates",
  "electromagnetic wave",
  "chemical reaction",
  "centrifuge",
  "particle accelerator",
  // History/Culture
  "colosseum",
  "sphinx",
  "stonehenge",
  "parthenon",
  "great wall",
  "trojan horse",
  "samurai",
  "gladiator",
  "pharaoh",
  "viking longship",
  "renaissance painting",
  "totem pole",
  "gargoyle",
  "flying buttress",
  // Mythology
  "minotaur",
  "phoenix",
  "kraken",
  "cerberus",
  "medusa",
  "pegasus",
  "hydra",
  "chimera",
  "cyclops",
  "griffin",
  // Emotions/States
  "betrayal",
  "redemption",
  "obsession",
  "enlightenment",
  "melancholy",
  "euphoria",
  "paranoia",
  "ambivalence",
  "hubris",
  "catharsis",
  // Complex scenes
  "shipwreck",
  "avalanche",
  "stampede",
  "coup d'etat",
  "heist",
  "interrogation",
  "stakeout",
  "duel",
  "ceremony",
  "coronation",
  // Technology
  "hologram",
  "artificial intelligence",
  "blockchain",
  "virtual reality",
  "quantum computer",
  "satellite",
  "space station",
  "solar panel",
  "wind turbine",
  "nuclear reactor",
  // Art/Music
  "symphony",
  "ballet",
  "opera",
  "fresco",
  "mosaic",
  "sculpture",
  "pottery wheel",
  "darkroom",
  "film noir",
  "impressionism",
  // Nature (complex)
  "bioluminescence",
  "migration",
  "hibernation",
  "camouflage",
  "symbiosis",
  "food chain",
  "ecosystem",
  "erosion",
  "fossil",
  "amber",
  // Professions (complex)
  "archaeologist",
  "cryptographer",
  "cartographer",
  "sommelier",
  "taxidermist",
  "epidemiologist",
  "forensic scientist",
  "paleontologist",
  // Idioms/Expressions
  "elephant in the room",
  "burning bridges",
  "tip of the iceberg",
  "pandoras box",
  "achilles heel",
  "trojan horse",
  "catch 22",
  "red herring",
  "wild goose chase",
  "slippery slope",
  // Misc complex
  "monopoly",
  "chess checkmate",
  "rube goldberg machine",
  "perpetual motion",
  "optical illusion",
  "tesseract",
  "mobius strip",
  "fractal",
  "standing ovation",
  "plot twist",
];

/**
 * Get the word list for a given complexity.
 */
export function getWordList(complexity: Complexity): string[] {
  switch (complexity) {
    case "kids":
      return KIDS_WORDS;
    case "standard":
      return STANDARD_WORDS;
    case "advanced":
      return ADVANCED_WORDS;
  }
}

/**
 * Pick a random word from the appropriate word list, avoiding already-used words.
 */
export function pickRandomWord(complexity: Complexity, usedWords: Set<string>): string {
  const words = getWordList(complexity);
  const available = words.filter((w) => !usedWords.has(w));
  if (available.length === 0) {
    // All words used, reset
    usedWords.clear();
    return pickRandom(words) ?? "cat";
  }
  return pickRandom(available) ?? "dog";
}
